name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for Lambda function
        run: zip -j code.zip src/etl_raw_to_rawplus.py
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update Lambda Function Code
        run: "aws lambda update-function-code \
            --function-name arn:aws:lambda:us-east-1:925680695682:function:etl_raw_to_rawplus \
            --zip-file fileb://code.zip"
      - name: Upload glue script to S3
        run: "aws s3 cp src/etl_glue_job.py s3://bdx-cicd/etl_glue_job.py"
      - name: Update Glue job
        run: "aws glue update-job \
            --job-name etl_raw_to_rawplus \
            --job-update '{\"Command\": {\"Name\": \"glueetl\", \"ScriptLocation\": \"s3://bdx-cicd/etl_glue_job.py\", \"Role\": \"arn:aws:iam::925680695682:role/glue-service-role\"}}'"